name: Update dynamic information
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-dynamic-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run update scripts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python build_tools/generate_scikit_learn_prs.py

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dynamic information
          branch: update-dynamic-info
          body: |
            - Update the list of scikit-learn contributions
